---
title: "House Stats"
author: "Savannah Tjaden"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Each house:
Overall Winning %
Graph of battle types with wins
Table of min/max army Size


```{r}

library(readr)
library(tidyverse)
library(readxl)
library(knitr)



house_stats_summary <- read_excel("house_stats.xlsx")

#create data frame for % wins
house_stats_summary <-house_stats_summary %>% 
  mutate(percent_win = ((wins/total_battles)*100)) 


house_stats <- read_excel("house_stats.xlsx", 
    sheet = "Sheet1")

house_stats$outcome <- as.factor(house_stats$outcome)
house_stats$battle_type <- as.factor(house_stats$battle_type)
house_stats$house <- as.factor(house_stats$house)


```

Baratheon
```{r}


#create data frame with just baratheon info
baratheon <- house_stats %>% 
  filter(house == "Baratheon")


#baratheon outcomes by battle type

ggplot(baratheon, aes(x=battle_type))+
  geom_bar(aes(fill= outcome), position = "stack") +
  theme_classic() +
  theme(legend.position = "", 
        title = element_text(size=20, face = "bold"),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15)
        ) +
  scale_fill_manual(values = c("red", "darkgreen")) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 6), breaks = c(0,1,2,3,4,5)) +
  ylab("")  +
  xlab("") +
  ggtitle("Baratheon")+
  coord_flip()


#baratheon table of army size

army_stats <- house_stats %>% 
  select(house, army_size) %>% 
  filter(house== "Baratheon")


plot(army_stats)

 ggplot(army_stats, aes(x= house, y=army_size)) +
      geom_boxplot(fill = "slateblue") +
      ylab("Army Size\n") +
      xlab("")+
      theme_classic() +
      theme(legend.position = "", 
            title = element_text(size=20, face = "bold"),
            plot.title = element_text(hjust = 0.5),
            axis.text.x = element_text(size = 15),
            axis.text.y = element_text(size = 15)
      )


```



```{r}

filter summary stats df based on alliances

experience score = sum(region) + sum(battle) 

army score = (input army size/ 100000) * 10

dragon score = 0 or 5

total <- sum of all these
  

if with dragons, then use with dragons score
if no dragons, use without score


```


```{r}

score <- house_stats_summary %>% 
  filter(house == "Baratheon" | house == "Lannister" | house == "Stark") %>% 
  select(pitched_battle, Riverlands) # input of battle type and input of region

battle_score = (sum(score$pitched_battle)/2) #input from battle type
region_score = (sum(score$Riverlands)/2.5) #input from region

army_score = ((50000/ 100000)*10) #input from slider bar/100,000

If input = "with dragons",
with_dragon_score = (battle_score + region_score + army_score + 10)
without_dragon_score = (battle_score + region_score + army_score)


survival_probability <- ((with_dragon_score / 40) * 100)




```

