---
title: "shiny_maps"
author: "Alexander Stejskal"
date: "February 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(tmap)
library(plotly)
library(leaflet)
library(htmltools)
library(readxl)
library(ggrepel)
#library(editData)
#library(forcats)
#library(dplyr)
```


```{r}
#house_stats <- read_excel("~/GOT/GOT_R/shiny_maps/house_stats.xlsx")

#battle_location <- read_excel("~/GOT/GOT_R/shiny_maps/battle_location.xlsx")

battle_location_map2 <- read_excel("battle_location_map2.xlsx")

```



```{r}
got_region <- st_read(dsn = ".", layer = "Political")
```





```{r}
got_region$name <- as.character(got_region$name)

got_region %>% 
  replace_na(list(name = "Beyond the Wall"))
```




```{r}
region_df <- full_join(got_region, battle_location_map2)
```



House dataframes
```{r}


df_baratheon <- region_df %>% 
  dplyr::select(name, Baratheon) %>% 
  replace_na(list(name = "Beyond the Wall", Baratheon = "0"))

df_baratheon$Baratheon <- as.numeric(as.character(df_baratheon$Baratheon))

df_bolton <- region_df %>% 
  dplyr::select(name, Bolton) %>% 
    replace_na(list(name = "Beyond the Wall", Bolton = "0"))
df_bolton$Bolton <- as.numeric(as.character(df_bolton$Bolton))

df_frey <- region_df %>% 
  dplyr::select(name, Frey) %>% 
    replace_na(list(name = "Beyond the Wall", Frey = "0"))
df_frey$Frey <- as.numeric(as.character(df_frey$Frey))

df_glover <- region_df %>% 
  dplyr::select(name, Glover) %>% 
    replace_na(list(name = "Beyond the Wall", Glover = "0"))
df_glover$Glover <- as.numeric(as.character(df_glover$Glover))

df_greyjoy <- region_df %>% 
  dplyr::select(name, Greyjoy) %>% 
    replace_na(list(name = "Beyond the Wall", Greyjoy = "0"))
df_greyjoy$Greyjoy<- as.numeric(as.character(df_greyjoy$Greyjoy))

df_karstark <- region_df %>% 
  dplyr::select(name, Karstark) %>% 
    replace_na(list(name = "Beyond the Wall", Karstark = "0"))
df_karstark$Karstark <- as.numeric(as.character(df_karstark$Karstark))

df_lannister <- region_df %>% 
  dplyr::select(name, Lannister) %>% 
    replace_na(list(name = "Beyond the Wall", Lannister = "0"))
df_lannister$Lannister <- as.numeric(as.character(df_lannister$Lannister))

df_mormont <- region_df %>% 
  dplyr::select(name, Mormont) %>% 
    replace_na(list(name = "Beyond the Wall", Mormont = "0"))
df_mormont$Mormont <- as.numeric(as.character(df_mormont$Mormont))

df_stark <- region_df %>% 
  dplyr::select(name, Stark) %>% 
    replace_na(list(name = "Beyond the Wall", Stark = "0"))
df_stark$Stark <- as.numeric(as.character(df_stark$Stark))

df_tully <- region_df %>% 
  dplyr::select(name, Tully) %>% 
    replace_na(list(name = "Beyond the Wall", Tully = "0"))
df_tully$Tully <- as.numeric(as.character(df_tully$Tully))

df_tyrell <- region_df %>% 
  dplyr::select(name, Tyrell) %>% 
    replace_na(list(name = "Beyond the Wall", Tyrell = "0"))
df_tyrell$Tyrell <- as.numeric(as.character(df_tyrell$Tyrell))
```




Baratheon map
```{r}
bar_points <- st_centroid(df_baratheon)
bar_points <- st_coordinates(bar_points$geometry)
bar_points <- cbind(df_baratheon, bar_points)

baratheon_map <- ggplot(df_baratheon) +
  geom_sf(aes(fill = Baratheon), color = "white", size = 0.2) +
  #scale_fill_gradient(colors = c("blue","mediumorchid1","orange")) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank())+
  geom_text(data = subset(bar_points, Baratheon != 0),
                  aes(x = X, y = Y, label = Baratheon),
            check_overlap = TRUE,
            color = "white")

baratheon_map

```


Bolton map
```{r}
bol_points <- st_centroid(df_bolton)
bol_points <- st_coordinates(bol_points$geometry)
bol_points <- cbind(df_bolton, bol_points)


bolton_map <- ggplot(df_bolton) +
  geom_sf(aes(fill = Bolton), color = "white", size = 0.2) +
  #scale_fill_gradient(colors = c("blue","mediumorchid1","orange")) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
               axis.title = element_blank())+
  geom_text(data = subset(bol_points, Bolton != 0),
                  aes(x = X, y = Y, label = Bolton),
            check_overlap = TRUE,
            color = "white")

bolton_map
```


Frey map
```{r}
frey_points <- st_centroid(df_frey)
frey_points <- st_coordinates(frey_points$geometry)
frey_points <- cbind(df_frey, frey_points)



               



frey_map <- ggplot(df_frey) +
  geom_sf(aes(fill = Frey), color = "white", size = 0.2) +
  #scale_fill_gradient(colors = c("blue","mediumorchid1","orange")) +
  theme_minimal() +
  theme(legend.position = 'none',
         axis.text = element_blank(),
        axis.title = element_blank())+
  geom_text(data = subset(frey_points, Frey != 0),
                  aes(x = X, y = Y, label = Frey),
            check_overlap = TRUE,
            color = "white")

frey_map
```


Glover map
```{r}

glo_points <- st_centroid(df_glover)
glo_points <- st_coordinates(glo_points$geometry)
glo_points <- cbind(df_glover, glo_points)



glover_map <- ggplot(df_glover) +
  geom_sf(aes(fill = Glover), color = "white", size = 0.2)+
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
        axis.title = element_blank())+
  geom_text(data = subset(glo_points, Glover != 0),
                  aes(x = X, y = Y, label = Glover),
            check_overlap = TRUE,
            color = "white")

glover_map
```


Greyjoy map
```{r}
gre_points <- st_centroid(df_greyjoy)
gre_points <- st_coordinates(gre_points$geometry)
gre_points <- cbind(df_greyjoy, gre_points)


greyjoy_map <- ggplot(df_greyjoy) +
  geom_sf(aes(fill = Greyjoy), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
        axis.title = element_blank())+
  geom_text(data = subset(gre_points, Greyjoy != 0),
                  aes(x = X, y = Y, label = Greyjoy),
            check_overlap = TRUE,
            color = "white")


greyjoy_map
```


Karstark map
```{r}
kar_points <- st_centroid(df_karstark)
kar_points <- st_coordinates(kar_points$geometry)
kar_points <- cbind(df_karstark, kar_points)

karstark_map <-ggplot(df_karstark) +
  geom_sf(aes(fill = Karstark), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(kar_points, Karstark != 0),
                  aes(x = X, y = Y, label = Karstark),
            check_overlap = TRUE,
            color = "white")

karstark_map
```


Lannister map
```{r}
lan_points <- st_centroid(df_lannister)
lan_points <- st_coordinates(lan_points$geometry)
lan_points <- cbind(df_lannister, lan_points)


lannister_map <- ggplot(df_lannister) +
  geom_sf(aes(fill = Lannister), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(lan_points, Lannister != 0),
                  aes(x = X, y = Y, label = Lannister),
            check_overlap = TRUE,
            color = "white")

lannister_map
```


Mormont map
```{r}
mor_points <- st_centroid(df_mormont)
mor_points <- st_coordinates(mor_points$geometry)
mor_points <- cbind(df_mormont, mor_points)


mormont_map <- ggplot(df_mormont) +
  geom_sf(aes(fill = Mormont), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(mor_points, Mormont != 0),
                  aes(x = X, y = Y, label = Mormont),
            check_overlap = TRUE,
            color = "white")

mormont_map
```


Stark map
```{r}
sta_points <- st_centroid(df_stark)
sta_points <- st_coordinates(sta_points$geometry)
sta_points <- cbind(df_stark, sta_points)


stark_map <- ggplot(df_stark) +
  geom_sf(aes(fill = Stark), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(sta_points, Stark != 0),
                  aes(x = X, y = Y, label = Stark),
            check_overlap = TRUE,
            color = "white")

stark_map
```


Tully map
```{r}
tul_points <- st_centroid(df_tully)
tul_points <- st_coordinates(tul_points$geometry)
tul_points <- cbind(df_tully, tul_points)


tully_map <- ggplot(df_tully) +
  geom_sf(aes(fill = Tully), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(tul_points, Tully != 0),
                  aes(x = X, y = Y, label = Tully),
            check_overlap = TRUE,
            color = "white")

tully_map
```


Tyrell map
```{r}
tyr_points <- st_centroid(df_tyrell)
tyr_points <- st_coordinates(tyr_points$geometry)
tyr_points <- cbind(df_tyrell, tyr_points)


tyrell_map <- ggplot(df_tyrell) +
  geom_sf(aes(fill = Tyrell), color = "white", size = 0.2) +
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text = element_blank(),
         axis.title = element_blank())+
  geom_text(data = subset(tyr_points, Tyrell != 0),
                  aes(x = X, y = Y, label = Tyrell),
            check_overlap = TRUE,
            color = "white")

tyrell_map
```



```{r}

ggsave(filename = "Baratheon.png", plot = baratheon_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Bolton.png", plot = bolton_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Frey.png", plot = frey_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Glover.png", plot = glover_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Greyjoy.png", plot = greyjoy_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Karstark.png", plot = karstark_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Lannister.png", plot = lannister_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Mormont.png", plot = mormont_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Stark.png", plot = stark_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Tully.png", plot = tully_map, width = 1, height = 1.5, units = "in")
ggsave(filename = "Tyrell.png", plot = tyrell_map, width = 1, height = 1.5, units = "in")



```















